### ISSUE TITLE
facility 

### ISSUE THREAD

**Issue by tucachmo2202** [kouei/discrete-optimization#2]
With MIP solution for facility, is it necessary to run 10 million times for optimal results, isn't it?
And as I know, you just use 50 facilities to serve all customers, is it optimal solution? 
Thank you very much! This a nice git!

**Comment by kouei** [comment]
Since there is a local search part involved in my algorithm, it is not guaranteed to be optimal.

**Comment by tucachmo2202** [comment]
Yeah. Thanks!
